"$schema" = "https://esm.sh/wrangler@4.66.0/config-schema.json"
name = "hacknet-wiki"
compatibility_date = "2026-02-18"
workers_dev = false

[assets]
directory = "./docs/.vitepress/dist"
not_found_handling = "404-page"
